import pandas as po
df_students = po.read_csv("students.csv")
df_scores = po.read_csv("scores.csv")
#Ex1
df_students.info
print("FIRST 5 ROWS: ")
print(df_students.head(10))
print("NUMBERS OF ROWS AND COLS CONSECUTIVE: ")
print(df_students.shape)
df_students.tail()
print("COLS of name and GPA are: ")
print(df_students[["name","GPA"]])
print("COLS of GPA >= 3.5 are: ")
print(df_students[df_students["GPA"] >= 3.5])
print("COLS of GPA in ascending are: ")
print(df_students.sort_values("GPA"))
print("AVERAGE GPA BY MAJOR: ")
print(df_students.groupby("major")["GPA"].mean())
#ex2
print("Missing values in students.csv")
print(df_students.isnull().sum())
print("Missing values in scores.csv")
print(df_scores.isnull().sum())
print("ROWS AND COLS AFTER FILLING OR REMOVING DATAS")
df_students = df_students.dropna(subset = ["student_id"])
df_scores = df_scores.dropna(subset = ["student_id"])
print(df_students)
print(df_scores)
print("DATASETS AFTER MERGING 2 DATASETS: ")
df_merged = po.merge(df_students, df_scores, on="student_id", how="inner")
print(df_merged)
print("AVERAGE SCORES OF EACH STUDENTS ARE: ")
df_merged["avg"] = df_merged[["python","math","database"]].mean(axis = 1).round(2)
print(df_merged)
print("TOP 5 STUDENTS ARE: ")
print(df_merged.sort_values("avg",ascending = 0).head(5))
print("Average Score by Major")
print(df_merged.groupby("major")["avg"].mean().reset_index())